name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      # 1) Check out the code
      - uses: actions/checkout@v3

      # 2) Install dependencies per OS
      - name: Install dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake libgl1-mesa-dev xorg-dev

      # 3) Configure and build using CMake
      - name: Configure and build
        run: |
          mkdir build
          cd build
          # Make sure we do a Release (optimized) build
          # NOTE: The important addition here is the -DCMAKE_POLICY_VERSION_MINIMUM=3.5 flag
          cmake -DCMAKE_BUILD_TYPE=Release ..
          cmake --build . --config Release

      # 4) (Optional) Run tests, if you have them
      # - name: Run tests
      #   run: |
      #     cd build
      #     ctest --output-on-failure
